use existing has function, less code
apostrophecms/sanitize-html pull request #409
Opened 2020-09-03 11:23 UTC by boutell

2020-09-03 11:32 UTC, TrySound approved these changes

2020-09-03 13:36 UTC, abea approved these changes

2020-09-03 13:36 UTC, abea requested changes
It only needs the changelog and version update.

2020-09-04 13:38 UTC, abea approved these changes

2020-09-04 13:38 UTC, merged