Support wildcards in allowedClasses (update to #157)
apostrophecms/sanitize-html pull request #472
Opened 2021-04-25 02:33 UTC by zhangbenber

Support wildcards in `allowedClasses` like this:

```javascript
allowedClasses: {
  p: ["prefix-*"]
}
```

---

Useful especially for allowing the `language-xxx` syntax indicator classes in [highlight.js](https://highlightjs.org/).

Attempts have been made in #157, and here I tried to build up a glob map before the loop for better performance, the same as what was done for allowed Attributes. And the wildcard may match zero character for consistency with allowed Attributes too.

All tests passed.

2021-04-26 12:28 UTC, boutell requested changes
Looks good — please add to the README and the changelog.

2021-05-03 12:47 UTC, boutell requested changes
Please add to the changelog as well. Thanks!

2021-05-05 11:03 UTC, zhangbenber commented
> Please add to the changelog as well. Thanks!

Glad to, but version numbers and release date may change according to maintainers' schedule :)

2021-05-05 13:59 UTC, abea commented
True. We normally add new items under an `Unreleased` heading but that wasn't clear. We can take care of it.

2021-05-06 12:43 UTC, boutell approved these changes

2021-05-06 12:43 UTC, boutell commented
@abea would you mind taking care of the changelog and adding this to the release notes plan?

2021-05-18 21:20 UTC, merged