update README regarding TypeScript (#420)
apostrophecms/sanitize-html pull request #473
Opened 2021-04-30 06:08 UTC by jbdemonte

2021-05-04 15:02 UTC, abea requested changes

2021-05-04 15:02 UTC, abea commented on README.md
> +* Install it using npm  (or yarn):
Let's say, "Install the package:"

2021-05-04 15:04 UTC, abea commented on README.md
> +yarn add --dev @types/sanitize-html
I don't mind including both below, but here we don't need both and don't prioritize yarn.

2021-05-04 16:13 UTC, abea commented
@boutell Any thoughts before we merge?

2021-05-18 21:45 UTC, abea reviewed
Holding for @boutell 's review

2021-05-19 12:33 UTC, boutell approved these changes

2021-05-19 14:32 UTC, abea approved these changes

2021-05-19 14:32 UTC, merged