Fix #486: Return an empty string when input is a nullish HTML
apostrophecms/sanitize-html pull request #496
Opened 2021-09-21 10:26 UTC by postatum

Note that nullish values also include 0, but according to [this comment](https://github.com/apostrophecms/sanitize-html/pull/102#issuecomment-872242667) of a repo member: 
> In any case it is up to the caller to pass a string.

2021-09-21 12:30 UTC, boutell commented
If it has a `toString()` I think it should be left alone, `0` is an unusual input but no need to reject it. I suggest testing with `== null` instead. This matches only `null` and `undefined` which are the only cases that don't support `toString()` and thus have trouble.

2021-09-22 06:14 UTC, postatum commented
> If it has a toString() I think it should be left alone, 0 is an unusual input but no need to reject it. I suggest testing with == null instead. This matches only null and undefined which are the only cases that don't support toString() and thus have trouble.

I see. I've changed the test to `== null`.

2021-09-22 12:10 UTC, boutell approved these changes

2021-09-22 12:10 UTC, boutell requested changes
Would you kindly add a changelog entry? Thank you!

2021-09-23 04:28 UTC, postatum commented
> Would you kindly add a changelog entry? Thank you!

Done. Please let me know if that's an OK description.

2021-09-23 12:43 UTC, boutell approved these changes
Thanks!

2021-09-23 12:44 UTC, merged