Add `preserveEscapedAttributes` option to retain all attributes of escaped disallowed tags
apostrophecms/sanitize-html pull request #668
Opened 2024-07-08 14:11 UTC by benelliott

Fixes https://github.com/apostrophecms/sanitize-html/issues/540

## Summary

*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*

Add `preserveEscapedAttributes` option to allow attributes on escaped disallowed tags to be retained. Closes #540 

## What are the specific steps to test this change?

You can try the new behaviour by setting `preserveEscapedAttributes` to `true` when `disallowedTagsMode` is `'escape'` or `'recursiveEscape'`.

Added unit tests to PR. 

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [x] Related documentation has been updated
- [x] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2024-07-08 19:28 UTC, BoDonkey requested changes
At first blush, this looks good! Can you add another test to show that the `preserveEscapedAttributes` functions correctly with the other `disallowedTagsMode`, please? Thanks!

2024-07-09 09:00 UTC, benelliott commented
Thanks @BoDonkey, I've added another test case.

2024-07-23 09:25 UTC, BoDonkey approved these changes
Nice last test. I would prefer that the docs include an example, but I'm not going to require it. Sorry that this got overlooked for a time.

2025-04-28 09:10 UTC, benelliott commented
bump

2025-04-28 10:14 UTC, BoDonkey commented
Not sure how this keeps falling between the cracks for me. Apologies.
Overall this looks good to me. Thanks for keeping it opt-in and safe by default!

I would suggest slightly improving the README docs to emphasize that `preserveEscapedAttributes: true` is intended mainly for development or trusted workflows, and may preserve dangerous attributes as escaped text. Otherwise, I'm fine with approving this.

Are you able to resolve the merge conflicts?

2025-05-08 09:45 UTC, benelliott commented
Hi @BoDonkey, no worries. I've rebased on main and added your suggestion to the readme,

2025-05-08 13:16 UTC, BoDonkey commented
I want to run this by one more set of eyes. Thanks so much for sticking in there!

2025-05-12 12:49 UTC, boutell commented on README.md
> +if you set `disallowedTagsMode` to `recursiveEscape`, disallowed tags and their children will be escaped even for allowed tags:
Unrelated grammar fix

2025-05-12 12:49 UTC, boutell commented on README.md
> +By default, attributes are not preserved when tags are escaped. You can set `preserveEscapedAttributes` to `true` to
Once a tag and its attributes are escaped, there is no risk. Also it's not just "disallowed attributes," it's all of the attributes. It's not a "real tag" anymore so no need to make it sound dangerous.

2025-05-12 12:49 UTC, boutell approved these changes

2025-05-12 18:38 UTC, merged